### PR TITLE
modular indexing with nth

### PR DESCRIPTION
**Pull request by pjago**
this way we can easily access the latest values

### CODE REVIEW

**Comment by danielcompton** [comment]
@BrunoBonacci what do you think about this change?

**Comment by arrdem** [comment]
Why not support negative indices if we're gonna do this?

**Comment by BrunoBonacci** [comment]
I’m not too sure about this enhancement overall.
I’d like to understand better the purpose. 
Reid: what’s your idea for negative indices?

Bye
Bruno

**Comment by pjago** [comment]
@arrdem I would say the main use of this is to get negative indices.
@BrunoBonacci I see negative indices as a way to access from the latest values in the buffer.
It fits well when you only care for the latest N values of a [time series](https://en.wikipedia.org/wiki/Time_series).

**Comment by BrunoBonacci** [comment]
Great, I will add some doc and test and then cut a new release for this.

**Comment by BrunoBonacci** [comment]
this will be released with version `1.3.0`.

PS: @danielcompton could you please cut a new release?

**Comment by danielcompton** [comment]
Yep, all done: https://clojars.org/amalloy/ring-buffer/versions/1.3.0. Thanks!

**Comment by danielcompton** [comment]
@BrunoBonacci happy for you to announce this on the Clojure mailing list, e.t.c. if you like?

**Comment by BrunoBonacci** [comment]
done!

**Pull request merged**
